spring:
  redis:
    # 集群（分片）模式
    cluster:
      max-redirects: 3
      #节点
      nodes:
        - 81.70.169.208:6379
        - 42.192.165.91:6379
        - 121.4.120.215:6379
        - 81.70.169.208:6380
        - 42.192.165.91:6380
        - 121.4.120.215:6380
    # Redis服务器连接密码（默认为空）
    password: 123456
    #jedis连接池信息仅供参考
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        pool.max-idle: 8
        # 连接池中的最小空闲连接
        pool.min-idle: 0
